// export const getInputValues = {
//     patientName: document.getElementById("patientName").value,
//     patientCPF: document.getElementById("patientCPF").value,
//     patientDoB: document.getElementById("patientDoB").value,
//     patientPhone: document.getElementById("patientPhone").value,
//     patientEmail: document.getElementById("patientEmail").value,
//     patientSex: document.getElementById("patientSex").value,
//     patientOccupation: document.getElementById("patientOccupation").value,
//     patientCEP: document.getElementById("patientCEP").value,
//     patientSt: document.getElementById("patientSt").value,
//     patientNumber: document.getElementById("patientNumber").value,
//     patientComplement: document.getElementById("patientComplement").value,
//     patientNeighborhood: document.getElementById("patientNeighborhood").value,
//     patientCity: document.getElementById("patientCity").value,
//     patientState: document.getElementById("patientState").value,
//     adultName: document.getElementById("adultName").value,
//     adultCPF: document.getElementById("adultCPF").value,
//     adultPhone: document.getElementById("adultCPF").value,
//     adultEmail: document.getElementById("adultEmail").value,
//     adultCEP: document.getElementById("adultCEP").value,
//     adultSt: document.getElementById("adultSt").value,
//     adultNumber: document.getElementById("adultNumber").value,
//     adultComplement: document.getElementById("adultComplement").value,
//     adultNeighborhood: document.getElementById("adultNeighborhood").value,
//     adultCity: document.getElementById("adultCity").value,
//     adultState: document.getElementById("adultState").value,
// }
